apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
namespace: zoryqon-disaster-recovery
nameSuffix: -disaster-recovery
labels:
  - pairs: { zoryqon.io/environment: disaster-recovery }
